#!/bin/sh
if ! [ -x "$(command -v deno)" ]; then
  echo "Error deno is not installed!"
else
  case "$1" in
    "run")
      if [ -z $2 ]; then
        echo "Error: Cannot found project.";
      else
        MAP="$2/import_map.json";
        SERVER="$2/server.js";
        deno run --allow-net --allow-read --allow-run --unstable --import-map=$MAP $SERVER;
      fi
      exit 1;;
    *)
      deno run --allow-net --allow-read --allow-run heh.js $@;
      exit 1;;
  esac
fi
